twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    paths:
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/styles': css
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator

when@test:
    twig:
        strict_variables: true
